{
 "title": "Deeptalk",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Listeners",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT\n  *\nFROM\n  listeners" }
   ]
  },
  {
   "title": "Stats about Ages",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as \"time\",\n  min(age) as \"min\",\n  max(age) as \"max\",\n  avg(age) as \"avg\"\nFROM\n  listeners\n"
    }
   ]
  },
  {
   "title": "Age of Listeners",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as \"time\",\n  name as \"metric\",\n  age as \"value\"\nFROM\n  listeners\n"
    }
   ]
  }
 ]
}