apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-server
  name: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - image: postgres:latest
        name: postgres-server
        envFrom:
          - configMapRef:
              name: postgres
          - secretRef:
              name: postgres