apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-server
  name: postgres-server
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-server
  type: ClusterIP