apiVersion: v1
kind: Service
metadata:
  labels:
    app: deeptalk-app
  name: {{ .Release.Name }}-deeptalk-app
spec:
  ports:
  - port: {{ .Values.app.service.port }}
    protocol: TCP
    targetPort: 80
  type: {{ .Values.app.service.type }}
  selector:
    app: deeptalk-app