apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: {{ .Release.Name }}-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:1.8.0
        name: influxdb
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-influxdb