kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/static"