app:
  replicaCount: 3
  service:
    port: 80
    type: NodePort

influx:
  db: deeptalk
  service:
    port: 8086
    type: ClusterIP

grafana:
  secret: grafana
  service:
    port: 3000
    type: NodePort